spring.datasource.url=jdbc:mysql://dev-mysql.c43cuu6cm9gx.us-east-1.rds.amazonaws.com:3306/javaapp
spring.datasource.username=admin
spring.datasource.password=SecurePassword123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8080
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp
